table 'Location Table'
	lineageTag: 38943b7e-9de6-4ba1-a3fe-19484374ecff

	column LocationID
		dataType: int64
		formatString: 0
		lineageTag: d02f6996-8340-4563-80ca-b44ad6513893
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 9cfd36e7-718e-4005-b858-0b08ad4b34a9
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7fee9a6b-3556-4a6c-b8e1-a56bda33608e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	partition 'Location Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\DELL\Desktop\Uber Data\Location Table.xlsx"), null, true),
				    #"Location Table_Sheet" = Source{[Item="Location Table",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Location Table_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationID", Int64.Type}, {"Location", type text}, {"City", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

